eslint:
  enabled: false
  config_file: .eslintrc.yml
haml:
  enabled: true
  config_file: .haml-lint.yml
ruby:
  enabled: false
  config_file: .rubocop.yml
scss:
  enabled: false
  config_file: .scss-lint.yml
